# Generated by Django 5.0.1 on 2024-02-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslab",
            old_name="timetable_id",
            new_name="timetable",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="schedule_id",
            new_name="schedule",
        ),
    ]
