# Generated by Django 5.0.1 on 2024-02-12 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="has_timetable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_color",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_length",
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name="timetable",
            name="timetable_color",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
