# Generated by Django 5.0.1 on 2024-02-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0002_rename_timetable_id_timeslab_timetable_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeslab",
            old_name="task_id",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="timetable",
            old_name="user_id",
            new_name="user",
        ),
    ]
