# Generated by Django 5.0.1 on 2024-02-14 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0003_alter_schedule_schedule_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="day",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="task",
        ),
        migrations.RemoveField(
            model_name="timetable",
            name="timetable_color",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="schedule_color",
            field=models.CharField(default="#9292F0", max_length=255),
        ),
        migrations.AddField(
            model_name="timetable",
            name="days",
            field=models.ManyToManyField(to="timelyapp.day"),
        ),
        migrations.CreateModel(
            name="TimeSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(default=django.utils.timezone.now)),
                ("end_time", models.TimeField(default=django.utils.timezone.now)),
                ("tasks", models.ManyToManyField(to="timelyapp.task")),
            ],
        ),
        migrations.AddField(
            model_name="day",
            name="time_slabs",
            field=models.ManyToManyField(to="timelyapp.timeslab"),
        ),
    ]
