# Generated by Django 5.0.1 on 2024-02-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0003_rename_task_id_timeslab_task_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="schedule_id",
            new_name="schedule",
        ),
    ]
