# Generated by Django 5.0.1 on 2024-02-03 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0003_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
