# Generated by Django 5.0.1 on 2024-02-03 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0004_schedule_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="behaviour",
            field=models.IntegerField(
                choices=[
                    (1, "Lazy"),
                    (2, "Moderately Lazy"),
                    (3, "Moderately Hardworking"),
                    (4, "Hardworking"),
                ],
                default=3,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="longest_sitting_time",
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
    ]
