# Generated by Django 5.0.1 on 2024-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0005_schedule_behaviour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="tasks",
            field=models.ManyToManyField(blank=True, to="timelyapp.task"),
        ),
    ]
