# Generated by Django 5.0.1 on 2024-02-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0005_timetable_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="schedule_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="timelyapp.schedule",
            ),
            preserve_default=False,
        ),
    ]
