# Generated by Django 5.0.1 on 2024-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0005_alter_schedule_name_alter_schedule_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslab",
            name="task_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
