# Generated by Django 5.0.1 on 2024-02-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0007_alter_schedule_tasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="user",
            new_name="user_id",
        ),
    ]
