# Generated by Django 5.0.1 on 2024-02-03 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0008_rename_user_schedule_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="user_id",
        ),
        migrations.AddField(
            model_name="schedule",
            name="user_id",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
