# Generated by Django 5.0.1 on 2024-02-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0009_remove_schedule_user_id_schedule_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="name",
            field=models.CharField(default="", max_length=255, unique=True),
        ),
    ]
