# Generated by Django 5.0.1 on 2024-02-03 12:08

import django.db.models.deletion
import timelyapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timelyapp", "0010_alter_schedule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="user_id",
        ),
        migrations.AddField(
            model_name="schedule",
            name="user_id",
            field=models.ForeignKey(
                default=timelyapp.models.CustomUser,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
